import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "@/components/react-query-client-provider";
import { Toaster } from "@/components/ui/sonner"
import UserStoreProvider from "@/lib/providers/user-provider";
import { Header } from "@/components/common/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <UserStoreProvider>
          <div className="sticky top-0 z-50 bg-white shadow-lg text-black">
          <Header />
        </div>
            {children}
          </UserStoreProvider>
          <Toaster position="top-right" duration={3000} />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
